version: '3'

services:
  php-fpm:
    container_name: php-fpm-dev
    build:
      context: ./php
    tty: true
    volumes:
      - ./src:/usr/src
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/log:/var/log
    ports:
      - 8111:8000

  nginx:
    container_name: nginx-dev
    build:
      context: ./nginx
    depends_on:
      - php-fpm
    tty: true
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 10902:80